spring:
 datasource:
   url: jdbc:h2:mem:testdb
   driverClassName: org.h2.Driver
   username: sa
   password: password
 jpa:
  database-platform: org.hibernate.dialect.H2Dialect
#  show-sql: true
  hibernate.ddl-auto: update
  properties:
    hibernate:
      jdbc:
        batch_size: 1000
 h2:
  console:
    enabled: true

#spring.datasource.url=jdbc:h2:file:/data/demo - for file based storage

